🚀 JReleaser {{projectVersion}} has been released! {{releaseNotesUrl}}
😅 This is mostly a fix release with a handful of enhancements. We'd like to thank our most recent contributors https://github.com/jreleaser/jreleaser/blob/main/CONTRIBUTORS.md
📣 Links in Bluesky announcer will be automatically converted to markdown links
📦 Homebrew packager now supports defining custom download strategy and additional require relative statements
🗒️  Changelog commits can now be identified by author/contributor, not just title and body
🏗️  Several updates to hooks such as new session event, conditional evaluation, and access to stacktrace upon failure
☕️ Provide custom JAVA_OPTS to the launcher generated by the Jlink assembler
📝 Full list of changes available at the {{milestoneName}} milestone {{projectLinkVcsBrowser}}/milestones?state=closed
🙏 As always, feedback is welcome. Feel free to raise a ticket at {{projectLinkBugTracker}}