= JReleaser
:linkattrs:
:project-owner:   jreleaser
:project-name:    jreleaser
:project-group:   org.jreleaser
:project-version: 0.1.0

image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}.svg[Download, link="https://search.maven.org/#search|ga|1|{project-name}"]
image:https://img.shields.io/github/downloads/{project-name}/{project-name}/total[GitHub all releases]

---

Release Java projects quickly and easily with link:https://jreleaser.org[JReleaser]!

== Install

There are multiple choices depending on your preference.

=== CLI
The CLI can be installed in the following ways:

*homebrew tap* (only on OSX for now):
[source]
----
brew install jreleaser/tap/jreleaser
----

*scoop*:
[source]
----
scoop bucket add jreleaser https://github.com/jreleaser/scoop-bucket.git
scoop install jreleaser
----

*sdkman*:
[source]
----
sdk install jreleaser
----

*jbang*
[source]
.stable
----
// Download, cache, and run
jbang jreleaser@jreleaser <command> [<args>]
----
[source]
.early-access
----
// Download, cache, and run
jbang jreleaser_snapshot@jreleaser <command> [<args>]
----

*manually*:

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.

== Docker
You can run JReleaser as a docker image, skipping the need to have a pre-installed Java runtime. You must mount the
working directory at the `/workspace` volume, for example assuming the current directory is the starting point:

[source]
----
$ docker run -it --rm -v `(pwd)`:/workspace jreleaser/jreleaser-slim:<tag> <command> [<args>]
----

NOTE: The `--basedir` argument will be automatically set to `--basedir=/workspace`.

You may also need to map environment variables to the container, such as `JRELEASER_PROJECT_VERSION`,
`JRELEASER_GITHUB_TOKEN`, or others depending on your setup. Refer to the
link:https://jreleaser.org/guide/latest/configuration/environment.html[configuration] pages.

=== Maven
Configure the jreleaser-maven-plugin in your POM file

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<plugin>
  <groupId>org.jreleaser</groupId>
  <artifactId>jreleaser-maven-plugin</artifactId>
  <version>{project-version}</version>
</plugin>
----

=== Gradle
Configure the jreleaser-gradle-plugin in your `build.gradle` or `settings.gradle` file

[source,groovy]
[subs="attributes"]
.build.gradle
----
plugins {
    id 'org.jreleaser' version '{project-version}'
}
----

=== Ant
Download the jreleaser-ant-tasks ZIP bundle from the
link:https://github.com/jreleaser/jreleaser/releases[releases page] and unzip it in your project. Place all JARs inside
the `lib` folder. Create this folder if there is none. Add the following elements to your `build.xml` file

[source,xml]
[subs="verbatim,attributes"]
.build.xml
----
<path id="jreleaser.classpath">
    <fileset dir="lib">
        <include name="jreleaser-ant-tasks-{project-version}/*.jar"/>
    </fileset>
</path>

<import>
  <javaresource name="org/jreleaser/ant/targets.xml"
                classpathref="jreleaser.classpath"/>
</import>
----


