= JReleaser Docker Images

:project-owner:   jreleaser
:project-name:    jreleaser

== jreleaser-slim

image:https://img.shields.io/docker/pulls/{project-owner}/{project-owner}-slim?label={project-owner}-slim&logo=docker&logoColor=white["Docker Pulls {project-owner}-slim", link="https://hub.docker.com/r/{project-owner}/jreleaser-slim"]

Wraps the link:https://jreleaser.org/guide/latest/tools/jreleaser-cli.html[JReleaser CLI] with an Ubuntu based Docker image:
link:https://hub.docker.com/r/jreleaser/jreleaser-slim[jreleaser/jreleaser-slim]. +
This image may be used to run JReleaser without having a pre-installed Java runtime on your system.

IMPORTANT: Additional packaging options such as link:https://jreleaser.org/guide/latest/configuration/packagers/snap.html[Snapcraft] and
link:https://jreleaser.org/guide/latest/configuration/packagers/chocolatey.html[Chocolatey] are not available in this mode.

Every command exposed by link:https://jreleaser.org/guide/latest/tools/jreleaser-cli.html[JReleaser CLI] can be invoked with this image.

You must mount the working directory at the `/workspace` volume, for example assuming the current directory is the
starting point:

[source]
----
$ docker run -it --rm -v `(pwd)`:/workspace \
  jreleaser/jreleaser-slim:<tag> <command> [<args>]
----

NOTE: The `jreleaser` command will be automatically executed inside `/workspace`.

You may also need to map environment variables to the container, such as `JRELEASER_PROJECT_VERSION`,
`JRELEASER_GITHUB_TOKEN`, or others depending on your setup.

You can find the tag listing link:https://hub.docker.com/r/jreleaser/jreleaser-slim/tags[here].

== jreleaser-alpine

image:https://img.shields.io/docker/pulls/{project-owner}/{project-owner}-alpine?label={project-owner}-alpine&logo=docker&logoColor=white["Docker Pulls {project-owner}-alpine", link="https://hub.docker.com/r/{project-owner}/jreleaser-alpine"]

Wraps the link:https://jreleaser.org/guide/latest/tools/jreleaser-cli.html[JReleaser CLI] with an Alpine based Docker image:
link:https://hub.docker.com/r/jreleaser/jreleaser-alpine[jreleaser/jreleaser-alpine]. +
This image may be used to run JReleaser without having a pre-installed Java runtime on your system.

IMPORTANT: Additional packaging options such as link:https://jreleaser.org/guide/latest/configuration/packagers/snap.html[Snapcraft] and
link:https://jreleaser.org/guide/latest/configuration/packagers/chocolatey.html[Chocolatey] are not available in this mode.

Every command exposed by link:https://jreleaser.org/guide/latest/tools/jreleaser-cli.html[JReleaser CLI] can be invoked with this image.

You must mount the working directory at the `/workspace` volume, for example assuming the current directory is the
starting point:

[source]
----
$ docker run -it --rm -v `(pwd)`:/workspace \
  jreleaser/jreleaser-alpine:<tag> <command> [<args>]
----

NOTE: The `jreleaser` command will be automatically executed inside `/workspace`.

You may also need to map environment variables to the container, such as `JRELEASER_PROJECT_VERSION`,
`JRELEASER_GITHUB_TOKEN`, or others depending on your setup.

You can find the tag listing link:https://hub.docker.com/r/jreleaser/jreleaser-alpine/tags[here].

== jreleaser-ubi

image:https://img.shields.io/docker/pulls/{project-owner}/{project-owner}-ubi?label={project-owner}-ubi&logo=docker&logoColor=white["Docker Pulls {project-owner}-ubi", link="https://hub.docker.com/r/{project-owner}/jreleaser-ubi"]

Wraps the link:https://jreleaser.org/guide/latest/tools/jreleaser-cli.html[JReleaser CLI] with a link:https://catalog.redhat.com/en/software/base-images[Red Hat Universal Base Image]:
link:https://hub.docker.com/r/jreleaser/jreleaser-ubi[jreleaser/jreleaser-ubi]. +
This image may be used to run JReleaser without having a pre-installed Java runtime on your system.

IMPORTANT: Additional packaging options such as link:https://jreleaser.org/guide/latest/configuration/packagers/snap.html[Snapcraft] and
link:https://jreleaser.org/guide/latest/configuration/packagers/chocolatey.html[Chocolatey] are not available in this mode.

Every command exposed by link:https://jreleaser.org/guide/latest/tools/jreleaser-cli.html[JReleaser CLI] can be invoked with this image.

You must mount the working directory at the `/workspace` volume, for example assuming the current directory is the
starting point:

[source]
----
$ docker run -it --rm -v `(pwd)`:/workspace \
  jreleaser/jreleaser-ubi:<tag> <command> [<args>]
----

NOTE: The `jreleaser` command will be automatically executed inside `/workspace`.

You may also need to map environment variables to the container, such as `JRELEASER_PROJECT_VERSION`,
`JRELEASER_GITHUB_TOKEN`, or others depending on your setup.

You can find the tag listing link:https://hub.docker.com/r/jreleaser/jreleaser-ubi/tags[here].
