Package: {{debControlPackage}}
Version: {{debControlVersion}}-{{debControlRevision}}
Maintainer: {{debControlMaintainer}}
Section: {{debControlSection}}
Priority: {{debControlPriority}}
Provides: {{debControlProvides}}
Architecture: {{debControlArchitecture}}
Installed-Size: {{debControlInstalledSize}}
Essential: {{debControlEssential}}
Description: {{debControlDescription}}
Homepage: {{debControlHomepage}}
{{#debControlBuiltUsing}}Built-Using: .{{/debControlBuiltUsing}}
{{#debControlDepends}}Depends: {{.}}{{/debControlDepends}}
{{#debControlPreDepends}}Pre-Depends: {{.}}{{/debControlPreDepends}}
{{#debControlRecommends}}Recommends: {{.}}{{/debControlRecommends}}
{{#debControlSuggests}}Suggests: {{.}}{{/debControlSuggests}}
{{#debControlEnhances}}Enhances: {{.}}{{/debControlEnhances}}
{{#debControlBreaks}}Breaks: {{.}}{{/debControlBreaks}}
{{#debControlConflicts}}Conflicts: {{.}}{{/debControlConflicts}}
