JReleaser {{projectVersion}} is now available! This release brings the following features:

This is mostly a fix release with a handful of enhancements. We'd like to thank our most recent [contributors](https://github.com/jreleaser/jreleaser/blob/main/CONTRIBUTORS.md)

**Announce:** Links in Bluesky announcer will be automatically converted to markdown links.

**Package:** Homebrew packager now supports defining custom download strategy and additional require relative statements.

**Changelog:**️ Changelog commits can now be identified by author/contributor, not just title and body.

**Hooks:**️ Several updates to hooks such as new session event, conditional evaluation, and access to stacktrace upon failure.

**Assemble:** Provide custom JAVA_OPTS to the launcher generated by the Jlink assembler.

[🚀 Changelog](https://github.com/jreleaser/jreleaser/releases/tag/{{tagName}}) [📝 Milestone]({{projectLinkVcsBrowser}}/milestone/26?closed=1)
