name: Clear cache

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  clear:
    name: Delete all caches
    runs-on: ubuntu-latest
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@e7ab82e64c328fd39c2e96933d426cd72ac2beba
