name: X-JPackage

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      project-effective-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  jpackage:
    name: '${{ matrix.job.jdkOs }}'
    strategy:
      fail-fast: false
      matrix:
        job:
          - { runner: ubuntu-latest,    platform: linux-x86_64,   platformReplaced: linux-x86_64,   jdkOs: Linux }
          - { runner: ubuntu-22.04-arm, platform: linux-aarch_64, platformReplaced: linux-aarch64,  jdkOs: LinuxArm }
          - { runner: macos-15-intel,   platform: osx-x86_64,     platformReplaced: osx-x86_64,     jdkOs: Osx }
          - { runner: macos-15,         platform: osx-aarch_64,   platformReplaced: osx-aarch64,    jdkOs: OsxArm }
          - { runner: windows-latest,   platform: windows-x86_64, platformReplaced: windows-x86_64, jdkOs: Windows }
    runs-on: ${{ matrix.job.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts
          path: plugins

      - name: Download jlink
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: jlink
          path: out/jreleaser/assemble/jreleaser-standalone/jlink

      - name: Expand jlink
        shell: bash
        run: |
          cd out/jreleaser/assemble/jreleaser-standalone/jlink
          ls -l
          unzip -q -d work-${{ matrix.job.platform }} jreleaser-standalone-${{ inputs.project-effective-version }}-${{ matrix.job.platformReplaced }}.zip

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRO }}
          cache: gradle

      - name: Version
        if: ${{ endsWith(inputs.project-version, '-SNAPSHOT') != true }}
        run: |
          echo ${{ inputs.project-version }} > VERSION

      - name: Jdks
        shell: bash
        run: |
          rm -rf ~/.gradle/caches/jdks/
          rm -rf plugins/jreleaser/build/jdks/
          ./gradlew :jreleaser:downloadJdkZulu25${{ matrix.job.jdkOs }} :jreleaser:verifyJdkZulu25${{ matrix.job.jdkOs }} :jreleaser:unpackJdkZulu25${{ matrix.job.jdkOs }}

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2

      - name: Jpackage
        uses: jreleaser/release-action@90ac653bb9c79d11179e65d81499f3f34527dcd5 # v2.5.0
        with:
          version: early-access
          arguments: assemble --assembler jpackage --select-current-platform
          setup-java: false
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: jreleaser-jpackage-${{ runner.os }}-${{ runner.arch }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Upload jpackage
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          retention-days: 1
          name: jpackage-${{ runner.os }}-${{ runner.arch }}
          path: |
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.pkg
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.msi
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.exe
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.deb
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.rpm

      - name: Stop Gradle daemon
        shell: bash
        run: ./gradlew -stop
