name: Trigger Early Access

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  earlyaccess:
    name: Trigger Early Access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRO }}

      - name: Build
        run: ./gradlew -PreproducibleBuild=true build -S

      - name: Rename artifacts
        run: |
          mkdir early-access
          cp plugins/jreleaser-tool-provider/build/VERSION early-access/VERSION
          cp plugins/jreleaser-tool-provider/build/libs/jreleaser-tool-provider-*-SNAPSHOT.jar early-access/jreleaser-tool-provider-early-access.jar
          cp plugins/jreleaser/build/distributions/jreleaser-*-SNAPSHOT.zip early-access/jreleaser-early-access.zip
          cp plugins/jreleaser-ant-tasks/build/distributions/jreleaser-ant-tasks-*-SNAPSHOT.zip early-access/jreleaser-ant-tasks-early-access.zip

      - name: Release early-access artifacts
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe #v2.6.1
        with:
          generate_release_notes: false
          tag_name: early-access
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          prerelease: true
          name: JReleaser Early-Access
          files: |
            early-access/*
